import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Work from "./Work";
import HomePage from "./HomePage";
import Skills from "./Skills";
import Contact from "./Contact";
import{SunIcon ,MoonIcon} from "@heroicons/react/solid";

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <Skills />
      <Work />
      <Contact />
    </div>
  );
};

export default Home;
